### ISSUE TITLE
Feature Request - Output as JSON

### ISSUE THREAD

**Issue by PenguinzPlays** [wzv5/pping#5]
Any chance you can outpost the results in a json structure format?

Love the tool, thanks!

**Comment by wzv5** [comment]
Can you provide some examples? I'm not sure how to output the results as json.

**Comment by wzv5** [comment]
I mean, this program outputs results in real time, so it's not suitable for outputting json results like this.

**Comment by PenguinzPlays** [comment]
Even if it was for aforementioned:
